'use client';

import { ThemeProvider } from 'styled-components';

import { GlobalStyle } from '@/styles/global';
import { Theme } from '@/styles/theme';
import { AppProvider } from '@/hooks';

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <ThemeProvider theme={Theme}>
            <AppProvider>
                <html lang="pt-br">
                    <head>
                        <title>Octagon Engenharia</title>
                        <meta
                            name="description"
                            content="Generated by create next app"
                        />
                        <link
                            rel="preconnect"
                            href="https://fonts.googleapis.com"
                        />
                        <link
                            rel="preconnect"
                            href="https://fonts.gstatic.com"
                            crossOrigin="use-credentials"
                        />
                        <link
                            href="https://fonts.googleapis.com/css2?family=Bai+Jamjuree:wght@400;500;600;700&family=Inter:wght@400;600;700;800&display=swap"
                            rel="stylesheet"
                        />
                    </head>
                    <body>{children}</body>
                </html>
            </AppProvider>
            <GlobalStyle />
        </ThemeProvider>
    );
}
