import RootLayout from './layout';
import type { Metadata } from 'next';

import { Home } from '../containers/Home';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Page() {
  return (
    <RootLayout>
      <Home />
    </RootLayout>
  );
}
